title: Prof. Dr. Ambuj Varshney ( ambujv@nus.edu.sg )
url: "https://ambuj.se"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Teaching"
   link: "cs6204"