title: Prof. Ambuj Varshney
url: "/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Teaching"
   link: "teaching"
 - name: "Opportunities"
   link: "position"
 - name: "Background"
   link: "background"
 - name: "STICORS"
   link: "stico"
 - name: "Beyond RF"
   link: "brf"
 - name: "ExaHAL"
   link: "exahal"
 - name: "Articles"
   link: "articles"
