title: Prof. Ambuj Varshney
url: "/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Teaching"
   link: "teaching"
 - name: "Open positions"
   link: "position"
 - name: "Projects"
   link: "projects"
 - name: "Background"
   link: "background"
 - name: "Sticker Computers (STICORS)"
   link: "stico"
 - name: "Beyond RF"
   link: "brf"