title: Prof. Ambuj Varshney ( ambujv@nus.edu.sg )
url: "/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Teaching"
   link: "cs6204"